### PR TITLE
Begin a page that gives an overview of the compiler

### PR DESCRIPTION
**Pull request by brendanzab**

### CODE REVIEW

**Comment by brendanzab** [comment]
For some reason the fixed width font that mdBook uses messes up the alignment of the box drawing characters:

screen shot 2018-06-23 at 8 31 41 pm

😭

**Comment by brendanzab** [comment]
Maybe I need to get some flow chart generator thing (graphvis perhaps?) working in the document build pipeline...

**Comment by brendanzab** [comment]
Switched to [svgbob](https://github.com/ivanceras/svgbobrus) for the diagrams. Unfortunately it's not supported by mdBook, but perhaps we could split it out into a preprocessing step at some stage. At least it renders fine in monospace now!

**Comment by adrianwong** [comment]
Didn't realise you were working on this! I was just about to send through a high-res screenshot of the diagram to use in the interim.

Happy to know you've found a temporary solution though!

**Comment by brendanzab** [comment]
Hopefully the further exposition has helped explain some more things too. 😄

**Comment by adrianwong** [comment]
Yeah, most definitely. Thanks for taking the time to write this up! 👍

**Pull request merged**
